# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yu8kVBD5MeXT-WyBxWTua68j34ra8ISf
"""

# BANNER 3 ANIMADO - CIBERSEGURIDAD GOODJOB
# David Agudiez Andres - 11 NOVIEMBRE 2025

import time
import os
from IPython.display import clear_output

# Colores ANSI
ROJO = "\033[91m"
VERDE = "\033[92m"
AMARILLO = "\033[93m"
AZUL = "\033[94m"
MAGENTA = "\033[95m"
CIAN = "\033[96m"
BLANCO = "\033[97m"
RESET = "\033[0m"
NEGRITA = "\033[1m"

# Banner ASCII
banner = f"""
  {AZUL}██████╗ {VERDE}██╗   ██╗{AMARILLO}████████╗{ROJO}██╗  ██╗ {CIAN}██████╗ {MAGENTA}███╗   ██╗{RESET}
  {AZUL}██╔══██╗{VERDE}╚██╗ ██╔╝{AMARILLO}╚══██╔══╝{ROJO}██║  ██║{CIAN}██╔═══██╗{MAGENTA}████╗  ██║{RESET}
  {AZUL}██████╔╝{VERDE} ╚████╔╝ {AMARILLO}   ██║   {ROJO}███████║{CIAN}██║   ██║{MAGENTA}██╔██╗ ██║{RESET}
  {AZUL}██╔═══╝ {VERDE}  ╚██╔╝  {AMARILLO}   ██║   {ROJO}██╔══██║{CIAN}██║   ██║{MAGENTA}██║╚██╗██║{RESET}
  {AZUL}██║     {VERDE}   ██║   {AMARILLO}   ██║   {ROJO}██║  ██║{CIAN}╚██████╔╝{MAGENTA}██║ ╚████║{RESET}
  {AZUL}╚═╝     {VERDE}   ╚═╝   {AMARILLO}   ╚═╝   {ROJO}╚═╝  ╚═╝{CIAN} ╚═════╝ {MAGENTA}╚═╝  ╚═══╝{RESET}

   {NEGRITA}{CIAN}>>> CURSO CIBERSEGURIDAD GOODJOB <<<{RESET}
   {NEGRITA}{VERDE}>>> DAVID AGUDIEZ ANDRES <<<{RESET}
   {NEGRITA}{AMARILLO}>>> 11 NOVIEMBRE 2025 <<<{RESET}
"""

# Animación: parpadeo + cambio de color
colores = [ROJO, VERDE, AMARILLO, AZUL, MAGENTA, CIAN]
for i in range(12):  # 12 ciclos (6 segundos)
    clear_output(wait=True)
    color_actual = colores[i % len(colores)]
    print(color_actual + banner.replace(">>>", f"{NEGRITA}>>>") + RESET)
    time.sleep(0.5)

# Versión final estática (brillante)
clear_output(wait=True)
print(f"{BLANCO}{NEGRITA}" + banner.replace(">>>", "✨ >>>") + RESET)
print(f"\n{NEGRITA}{CIAN}  ¡TE LO HAS CURRADO CAMPEÓN!{RESET} {VERDE}✓{RESET}")