# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkZT6Bgq9r3gVItxYh0YBjuBxVsL-mdq
"""

#!/usr/bin/env python3
"""
Banner ASCII GOODJOB - Versión para Google Colab
Curso de Ciberseguridad - Fundación GOODJOB
Fecha: 16 de noviembre de 2025
"""

import subprocess
from datetime import datetime

# Instalar dependencias en Colab
print("📦 Instalando dependencias...")
!apt-get install -y figlet cowsay > /dev/null 2>&1

print("="*70)
print("CURSO DE CIBERSEGURIDAD - PROGRAMACIÓN PYTHON")
print("Fundación GOODJOB")
print("="*70)
print(f"\n📅 Fecha: {datetime.now().strftime('%d de %B de %Y')}")

print("\n1️⃣ PRINT BÁSICO:")
print("-"*70)
print("GOODJOB")

print("\n2️⃣ BANNER CON FIGLET:")
print("-"*70)
!figlet GOODJOB

print("\n3️⃣ MENSAJE CON COWSAY:")
print("-"*70)
!cowsay "Fundacion GoodJob - Ciberseguridad 2025"

print("\n4️⃣ BANNER ALTERNATIVO:")
print("-"*70)
!figlet -f banner GOODJOB

print("\n" + "="*70)
print("✅ Script completado exitosamente")
print(f"⏰ Hora: {datetime.now().strftime('%H:%M:%S')}")
print("="*70)